minVersion: "0.18.0"
github:
  owner: getsentry
  repo: sentry-android-gradle-plugin
changelogPolicy: simple
statusProvider:
  name: github
artifactProvider:
  name: none
targets:
  - name: github
  - name: registry
    type: sdk
    config:
      canonical: "maven:io.sentry:sentry-android-gradle-plugin"
