minVersion: 0.25.2
changelogPolicy: auto
targets:
  - name: maven
    gradleCliPath: ./gradlew
    mavenCliPath: scripts/mvnw
    mavenSettingsPath: scripts/settings.xml
    mavenRepoId: ossrh
    mavenRepoUrl: https://oss.sonatype.org/service/local/staging/deploy/maven2/
    android: false
  - name: github
  - name: registry
    sdks:
      maven:io.sentry:sentry-android-gradle-plugin:
