/**
 * Adapted from https://github.com/autonomousapps/dependency-analysis-gradle-plugin/blob/1033bad8a8fe15c53c9095293eb97e79890ea63f/src/main/kotlin/com/autonomousapps/internal/artifacts/Resolver.kt
 *
 * Copyright 2024 Anthony Robalik
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package io.sentry.gradle.artifacts

import org.gradle.api.Named
import org.gradle.api.NamedDomainObjectProvider
import org.gradle.api.Project
import org.gradle.api.artifacts.Configuration

/**
 * Used for resolving custom artifacts in an aggregating project (often the "root" project), from producing projects
 * (often all or a subset of the subprojects ina build). Only for inter-project publishing and resolving (e.g., _not_
 * for publishing to Artifactory). See also [Publisher].
 *
 * Represents a set of tightly coupled [Configuration]s:
 * * A "dependency scope" configuration ([declarable]).
 * * A "resolvable" configuration ([internal]).
 * * A "consumable" configuration ([Publisher.external]).
 *
 * Dependencies are _declared_ on [declarable], and resolved within a project via [internal]. Custom artifacts (e.g.,
 * not jars), generated by tasks, are published via [Publisher.publish], which should be used on dependency
 * (artifact-producing) projects.
 *
 * Gradle uses [attributes][Attr] to wire the consumer project's [internal] (resolvable) configuration to the producer
 * project's [Publisher.external] (consumable) configuration, which is itself configured via [Publisher.publish].
 *
 * @see <a href="https://docs.gradle.org/current/userguide/cross_project_publications.html#sec:variant-aware-sharing">Variant-aware sharing of artifacts between projects</a>
 * @see <a href="https://dev.to/autonomousapps/configuration-roles-and-the-blogging-industrial-complex-21mn">Gradle configuration roles</a>
 */
internal class Resolver<T : Named>(
  project: Project,
  declarableName: String,
  attr: Attr<T>,
) {

  internal companion object {
    /** Convenience function for creating a [Resolver] for inter-project resolving of [DagpArtifacts]. */
    fun interProjectResolver(
      project: Project,
      artifact: SgpArtifacts.Kind,
    ): Resolver<SgpArtifacts> {
      return Resolver(
        project,
        artifact.declarableName,
        Attr(SgpArtifacts.SGP_ARTIFACTS_ATTRIBUTE, artifact.artifactName)
      )
    }
  }

  // Following the naming pattern established by the Java Library plugin. See
  // https://docs.gradle.org/current/userguide/java_library_plugin.html#sec:java_library_configurations_graph
  private val internalName = "${declarableName}Classpath"

  /** Dependencies are declared on this configuration */
  val declarable: Configuration = project.dependencyScopeConfiguration(declarableName).get()

  /**
   * The plugin will resolve dependencies against this internal configuration, which extends from
   * the declared dependencies.
   */
  val internal: NamedDomainObjectProvider<out Configuration> =
    project.resolvableConfiguration(internalName, declarable) { configuration ->
      // This attribute is identical to what is set on the external/consumable configuration
      configuration.attributes { attrs ->
        attrs.attribute(
          attr.attribute,
          project.objects.named(attr.attribute.type, attr.attributeName)
        )
        attrs.attribute(
          SgpArtifacts.CATEGORY_ATTRIBUTE,
          SgpArtifacts.category(project.objects)
        )
      }
    }
}
