package io.sentry.android.gradle.util

import java.io.StringWriter
import java.util.Properties
import kotlin.test.assertEquals
import kotlin.test.assertFalse
import kotlin.test.assertTrue
import org.junit.Test

class PropertiesUtilTest {

  @Test
  fun `store writes properties without timestamp`() {
    val props = Properties()
    props.setProperty("key1", "value1")
    props.setProperty("key2", "value2")

    val writer = StringWriter()
    PropertiesUtil.store(props, writer, "Test comment")
    val result = writer.toString()

    // should not contain date patterns that Java Properties.store() adds
    assertFalse(result.contains("Mon ") || result.contains("Tue ") || result.contains("Wed "))
    assertFalse(result.contains("Thu ") || result.contains("Fri ") || result.contains("Sat "))
    assertFalse(result.contains("Sun "))
    // should contain properties
    assertTrue(result.contains("key1=value1"))
    assertTrue(result.contains("key2=value2"))
    // should contain comment
    assertTrue(result.contains("# Test comment"))
  }

  @Test
  fun `store writes properties in sorted order`() {
    val props = Properties()
    props.setProperty("zebra", "last")
    props.setProperty("apple", "first")
    props.setProperty("middle", "mid")

    val writer = StringWriter()
    PropertiesUtil.store(props, writer)
    val result = writer.toString()

    val appleIndex = result.indexOf("apple=first")
    val middleIndex = result.indexOf("middle=mid")
    val zebraIndex = result.indexOf("zebra=last")

    assertTrue(appleIndex < middleIndex)
    assertTrue(middleIndex < zebraIndex)
  }

  @Test
  fun `store works without comment`() {
    val props = Properties()
    props.setProperty("key", "value")

    val writer = StringWriter()
    PropertiesUtil.store(props, writer)
    val result = writer.toString()

    assertFalse(result.contains("#"))
    assertEquals("key=value\n", result)
  }

  @Test
  fun `store produces identical output for same properties`() {
    val props = Properties()
    props.setProperty("io.sentry.build-tool", "gradle")
    props.setProperty("io.sentry.ProguardUuids", "test-uuid")

    val writer1 = StringWriter()
    PropertiesUtil.store(props, writer1, "Generated by sentry-android-gradle-plugin")

    val writer2 = StringWriter()
    PropertiesUtil.store(props, writer2, "Generated by sentry-android-gradle-plugin")

    assertEquals(writer1.toString(), writer2.toString())
  }
}
