name: Changelog Preview
on:
  pull_request:
    types:
    - opened
    - synchronize
    - reopened
    - edited
    - labeled
    - unlabeled
permissions:
  contents: write
  pull-requests: write
  statuses: write

jobs:
  changelog-preview:
    uses: getsentry/craft/.github/workflows/changelog-preview.yml@9a8e27a89529970cc0f241c6b77fdcbc32838c03 # v2
    secrets: inherit
