name: Test Maven Publish to Maven Local

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - '*'

jobs:
  publish-maven-local:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
      - name: Cache Gradle Files
        uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches/
            ~/.gradle/wrapper/
          key: cache-gradle-${{ matrix.os }}
          restore-keys: |
            cache-gradle-

      - name: Run publishToMavenLocal
        run: |
          cd plugin-build
          make dryRelease
