name: Test Publishing UUID

on:
  push:
    branches:
      - main
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  publish:
    runs-on: ubuntu-latest

    env:
      AUTO_UPLOAD: true
      SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}

    steps:
      - name: Checkout Repo
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@5e2ebd065dc2488b7a6ad670704656cbbe1e8f60 # pin@v6
        with:
          cache-encryption-key: ${{ secrets.GRADLE_ENCRYPTION_KEY }}

      - name: Build the Release variant
        run: ./gradlew assembleRelease --no-build-cache | tee gradle.log

      - name: Verify that Native Symbols were uploaded
        run: grep "Uploaded [1-9][0-9]* missing debug information file" gradle.log
        if: env.SENTRY_AUTH_TOKEN != null
